import "dotenv/config";
import AdmZip from "adm-zip";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Generates lib/cities.ts from the GeoNames "cities15000" dataset (all cities
// with population > 15,000). We guarantee the single largest city of every
// country (so every country is represented — not only capitals), then fill the
// remaining slots with the next-biggest metros worldwide, capped per country.
//
//   npm run gen:cities                 # ~300 cities (default)
//   CITY_TARGET=1000 npm run gen:cities
//   CITY_PER_COUNTRY=4 npm run gen:cities

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "lib", "cities.ts");
const URL = "https://download.geonames.org/export/dump/cities15000.zip";

const TARGET = clampInt(process.env.CITY_TARGET, 10, 25000, 300);
const PER_COUNTRY = clampInt(process.env.CITY_PER_COUNTRY, 1, 50, 3);

interface Row {
  name: string;
  country: string;
  lat: number;
  lon: number;
  population: number; // absolute people
}

async function main() {
  console.log(`Downloading GeoNames cities15000 …`);
  const res = await fetch(URL);
  if (!res.ok) throw new Error(`Download failed: ${res.status} ${res.statusText}`);
  const buf = Buffer.from(await res.arrayBuffer());

  const zip = new AdmZip(buf);
  const entry = zip.getEntry("cities15000.txt");
  if (!entry) throw new Error("cities15000.txt not found in archive");
  const text = entry.getData().toString("utf8");

  // GeoNames geoname schema (tab-separated):
  // 1 asciiname, 4 latitude, 5 longitude, 8 country code, 14 population
  const rows: Row[] = [];
  for (const line of text.split("\n")) {
    if (!line) continue;
    const f = line.split("\t");
    const name = f[2] || f[1];
    const lat = Number(f[4]);
    const lon = Number(f[5]);
    const country = f[8];
    const population = Number(f[14]);
    if (!name || !country || !Number.isFinite(lat) || !Number.isFinite(lon)) continue;
    if (!Number.isFinite(population) || population < 15000) continue;
    rows.push({ name, country, lat, lon, population });
  }
  console.log(`Parsed ${rows.length} cities (population > 15k).`);

  // Group by country, sort each country's cities by population desc.
  const byCountry = new Map<string, Row[]>();
  for (const r of rows) {
    const list = byCountry.get(r.country) ?? [];
    list.push(r);
    byCountry.set(r.country, list);
  }
  for (const list of byCountry.values()) {
    list.sort((a, b) => b.population - a.population);
  }

  const chosen: Row[] = [];
  const seen = new Set<Row>();

  // Pass 1 — guarantee the largest city of every country.
  for (const list of byCountry.values()) {
    if (list[0]) {
      chosen.push(list[0]);
      seen.add(list[0]);
    }
  }
  console.log(`Guaranteed 1 city for each of ${chosen.length} countries.`);

  // Pass 2 — fill the rest with the biggest remaining metros worldwide,
  // capped at PER_COUNTRY per country, until we reach TARGET.
  const remaining = rows
    .filter((r) => !seen.has(r))
    .sort((a, b) => b.population - a.population);
  const perCountryCount = new Map<string, number>();
  for (const r of chosen) {
    perCountryCount.set(r.country, (perCountryCount.get(r.country) ?? 0) + 1);
  }
  for (const r of remaining) {
    if (chosen.length >= TARGET) break;
    const n = perCountryCount.get(r.country) ?? 0;
    if (n >= PER_COUNTRY) continue;
    chosen.push(r);
    perCountryCount.set(r.country, n + 1);
  }

  // Sort final list by population desc for stable, readable output.
  chosen.sort((a, b) => b.population - a.population);

  const countriesCovered = new Set(chosen.map((c) => c.country)).size;
  console.log(
    `Selected ${chosen.length} cities across ${countriesCovered} countries.`
  );

  writeFileSync(OUT, render(chosen), "utf8");
  console.log(`Wrote ${OUT}`);
}

function render(rows: Row[]): string {
  const lines = rows.map((r) => {
    const name = JSON.stringify(r.name);
    const country = JSON.stringify(r.country);
    const lat = round(r.lat, 4);
    const lon = round(r.lon, 4);
    const pop = Math.max(1, Math.round(r.population / 1000)); // thousands
    return `  { name: ${name}, country: ${country}, lat: ${lat}, lon: ${lon}, population: ${pop} },`;
  });
  return `// AUTO-GENERATED by scripts/generate-cities.ts from the GeoNames
// "cities15000" dataset (CC BY 4.0, https://www.geonames.org/). Do not edit by
// hand — re-run \`npm run gen:cities\` to regenerate. population is in thousands;
// tz_offset is approximated from longitude at ingest time.
export interface CitySeed {
  name: string;
  country: string;
  lat: number;
  lon: number;
  population: number; // thousands
}

export const CITIES: CitySeed[] = [
${lines.join("\n")}
];
`;
}

function round(n: number, d: number): number {
  const f = 10 ** d;
  return Math.round(n * f) / f;
}

function clampInt(raw: string | undefined, lo: number, hi: number, dflt: number): number {
  const n = raw ? parseInt(raw, 10) : NaN;
  if (Number.isNaN(n)) return dflt;
  return Math.max(lo, Math.min(hi, n));
}

main().catch((err) => {
  console.error("\nGenerate failed:", err.message);
  process.exit(1);
});
